fix(mongo): fix support for deno by handling `TypedArray` when cloning (#7258)
This PR fixes the usage of `@mikro-orm/mongodb` with Deno.

## Issue

Using the newly added reproduction test case in
`tests/deno/mongodb.test.ts`, and running it with no additional code
change results in the following error:

```
> deno run --allow-read --allow-write --allow-env --allow-net --allow-sys --node-modules-dir=manual tests/deno/mongodb.test.ts
error: Uncaught (in promise) TypeError: this is not a typed array.
    at Uint8Array.values (<anonymous>)
    at Array.from (<anonymous>)
    at Object.toHex (file:///.../mikro-orm/node_modules/bson/lib/bson.cjs:481:22)
    at ObjectId.toHexString (file:///.../mikro-orm/node_modules/bson/lib/bson.cjs:2672:37)
    at eval (eval at createFunction (file:///.../mikro-orm/packages/core/src/utils/Utils.ts:900:14), <anonymous>:13:68)
    at ChangeSetComputer.computePayload (file:///.../mikro-orm/packages/core/src/unit-of-work/ChangeSetComputer.ts:145:20)
    at ChangeSetComputer.computeChangeSet (file:///.../mikro-orm/packages/core/src/unit-of-work/ChangeSetComputer.ts:61:56)
    at UnitOfWork.findNewEntities (file:///.../mikro-orm/packages/core/src/unit-of-work/UnitOfWork.ts:780:46)
    at UnitOfWork.computeChangeSets (file:///.../mikro-orm/packages/core/src/unit-of-work/UnitOfWork.ts:634:12)
    at UnitOfWork.doCommit (file:///.../mikro-orm/packages/core/src/unit-of-work/UnitOfWork.ts:514:12)
```

## Investigation

Why is this bug appearing with Deno? The behavior is different because
of [this line of code in the `bson`
package](https://github.com/mongodb/js-bson/blob/0712bb15653093766a80bbd4ba104353cd4581e3/src/utils/byte_utils.ts#L69):
- with Node.js, `Buffer.prototype?._isBuffer` is `undefined` ; so
`ByteUtils` is using `nodeJsByteUtils`
- with Deno, `Buffer.prototype?._isBuffer` is `true` ; so `ByteUtils` is
using `webByteUtils`

The content of the `fromHex` method is different in both
implementations:
- With `nodeJsByteUtils`, [it uses
`Buffer.from`](https://github.com/mongodb/js-bson/blob/0712bb15653093766a80bbd4ba104353cd4581e3/src/utils/node_byte_utils.ts#L150)
- with `webByteUtils`, [it uses
`Uint8Array.from`](https://github.com/mongodb/js-bson/blob/0712bb15653093766a80bbd4ba104353cd4581e3/src/utils/web_byte_utils.ts#L258)

The issue is that our `clone` function in
`packages/core/src/utils/clone.ts` does not handle cloning of
`Uint8Array` properly.

For instance, whit the following `Uint8Array` array:
```
Uint8Array(12) [
  105, 172, 10
]
```
Cloning it with our util function will result in:
```
Uint8Array {
  "0": 105,
  "1": 172,
  "2": 10
}
```

## Fix

In this PR, we add proper support for cloning [all `TypedArray`
subtypes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#typedarray_objects).