fix(core): check proptotype chain while cloning (#5979)
I'm using MikroORM 6.3.7 with Postgresql 14.

I'm using MikroORM with ts-jenum.
When I use [ts-jenum](https://github.com/reforms/ts-jenum) in MikroORM's
where condition, following error occurs

```
Cannot set property enumName of [object Object] which has only a getter
TypeError: Cannot set property enumName of [object Object] which has only a getter
```

This issue was caused by the [following
code](https://github.com/reforms/ts-jenum/blob/e1a45f54537ec5bd6abc258391e656e8c6339595/src/ts/jenum.ts#L181-L184).
In the ts-jenum library, the “enumName” of the parent enum type has a
getter but no setter implemented. Therefore, when [clone.ts tries to
call the
setter](https://github.com/mikro-orm/mikro-orm/blob/c0dacd8964786118d094fb6f88c3c136bcfa7115/packages/core/src/utils/clone.ts#L123),
an error occurs.

I explored why this issue occurs. The problem arises in MikroORM’s
“clone” function when using the `Object.getOwnPropertyDescriptor`
function. `Object.getOwnPropertyDescriptor` inspects the properties of a
JavaScript object but does not check the properties inherited from its
prototype. Therefore, I removed the `Object.getOwnPropertyDescriptor`
function in the clone operation and created a function that inspects the
properties of the object as well as those inherited from the connected
prototype.

---------

Co-authored-by: yakpoong <yakpoong@inflab.com>
Co-authored-by: Martin Adámek <banan23@gmail.com>